# Generated by Django 2.2.5 on 2019-09-27 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paynowpayment',
            old_name='additionalinfo',
            new_name='details',
        ),
    ]
