# Generated by Django 2.2.5 on 2019-09-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20190927_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paynowpayment',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
