# Generated by Django 2.2.5 on 2019-09-30 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20190927_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paynowpayment',
            old_name='browserurl',
            new_name='browser_url',
        ),
        migrations.RenameField(
            model_name='paynowpayment',
            old_name='pollurl',
            new_name='poll_url',
        ),
    ]
